services:
  mongodb:
    image: mongo
    restart: unless-stopped
    expose:
      - "27017"
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_USERNAME }}
      MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    # Uncomment when you need DB access, recomment and redeploy when done
    ports:
      - "8081:8081"
    expose:
      - "8081"
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${secrets.MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${secrets.MONGO_PASSWORD}
      ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"

  backend:
    # Each service now references its own dedicated ECR repository URL
    image: ${BACKEND_ECR_REPO_URL}:${IMAGE_TAG}
    restart: unless-stopped
    expose:
      - "5000"
    env_file:
      - .env
    depends_on:
      - mongodb

  frontend:
    image: ${FRONTEND_ECR_REPO_URL}:${IMAGE_TAG}
    restart: unless-stopped
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - backend
volumes:
  mongo_data:
