name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ env.AWS_REGION }}
  ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
  IMAGE_TAG: ${{ github.sha }}[1:7]

  # Secrets
  AWS_ROLE: ${{ secrets.AWS_ROLE_ARN }}
  ECR_REGISTRY: ${{ secrets.ECR_REPOSITORY_URL }}
  EC2_HOST: ${{ secrets.EC2_HOST }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: Build Image
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .

      - name: Tag Image
        run: |
          docker tag $ECR_REPOSITORY:$IMAGE_TAG \
          $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Push Image
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        run: |

          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@$EC2_HOST "

          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin $ECR_REGISTRY &&

          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG &&

          docker stop app || true &&
          docker rm app || true &&

          docker run -d --name app -p 80:3000 \
          $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          "
